### ISSUE TITLE
JS: Every so often, get Pizza Stock values

### ISSUE THREAD

**Issue by alfwall** [alfwall/catzzeria#10]
Every 1 minute (arbitrarily longer amount of time), check the value of [Pizza Company] stocks, print that number somewhere beneath the Pizza button

**Comment by lelisiario** [comment]
Some ideas for Pizza Stocks: 
https://finance.yahoo.com/news/10-best-pizza-stocks-buy-122014139.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAKIKpwoh9GNYrLa-6i6JQPBIaFoG7g4VY7teXqdWk7EsQaPy4V_rir8fQZv735XcYLfNPKtTg8m18is5cC2cORECJC5FKgXwqXAaY7OTzs5O6llC3T-KrAutDSoW-7kocQz9zPUbk2IieVquISW2leeytT-mZj6INNeNgGMLszpW

**Comment by nicolehekim** [comment]
intervals have been set to retrieve pizza stock, we have confirmed with console.log
