### ISSUE TITLE
JS: Reset modal + confirmation

### ISSUE THREAD

**Issue by alfwall** [alfwall/catzzeria#12]
Reset button should create a modal that asks if you're REALLY sure you wanna lose your save data (pizza count and cat count)

**Comment by talbdbd** [comment]
I would also suggest we add the hyde-chair.jpg to the modal

**Comment by alfwall** [comment]
We need a non-native JS modal to confirm before you reset your save data! What should we use?

**Comment by lelisiario** [comment]
React keeps coming up in search results. Is that native? Can we use that, or maybe there is a better one?

**Comment by lelisiario** [comment]
Created modal to create a pop up and ask confirmation to reset game progress.
