### ISSUE TITLE
JS: Replace "Start" button functionality with "Save" button

### ISSUE THREAD

**Issue by alfwall** [alfwall/catzzeria#13]
Top-left corner of the screen says "Start"- make it say "Save" instead, and then link that save function.

**Comment by talbdbd** [comment]
will do after we upload images

**Comment by talbdbd** [comment]
make sure id name is savebtn in order to conform with beercss format

**Comment by alfwall** [comment]
I'm going over this with Adjoa on her branch!

**Comment by AdjoaHackman** [comment]
Committed the changes
