### ISSUE TITLE
Cleaning up files

### ISSUE THREAD

**Issue by nicolehekim** [alfwall/catzzeria#16]
guide.html and style.css are not needed anymore as guide is not necessary for minimal viable product and style.css has been replaces with implementing BeerCSS

**Comment by lelisiario** [comment]
Yayy clean up!

**Comment by talbdbd** [comment]
makes sense to me

**Comment by alfwall** [comment]
Are we still using any of the styles from style.css? Have we tested it when the referenced stylesheet is removed from the HTML?

**Comment by talbdbd** [comment]
no, they're irrelevant, nicole tested and confirmed they're not needed

**Comment by nicolehekim** [comment]
> Are we still using any of the styles from style.css? Have we tested it when the referenced stylesheet is removed from the HTML?

Yes! have tested it out and can confirm that we can safely remove style.css without affecting anything

**Comment by talbdbd** [comment]
all unused files have been cleared out
