### ISSUE TITLE
Delete CSS Stylesheet to fix load error

### ISSUE THREAD

**Issue by lelisiario** [alfwall/catzzeria#21]
Error: Failed to load resource: net::ERR_FILE_NOT_FOUND - assets/css/style.css:1

![image](https://github.com/alfwall/catzzeria/assets/69616219/812262de-c848-40bc-b20d-0916580467ef)

**Comment by talbdbd** [comment]
will delete along with my cat count commit tomorrow (Wednesday, Mar 20)

**Comment by nicolehekim** [comment]
no longer need to delete, need style.css anyways to make it mobile friendly
