### ISSUE TITLE
JS: Cat Count should regularly increase Pizza Slice Count

### ISSUE THREAD

**Issue by alfwall** [alfwall/catzzeria#9]
Every 1 second, pizza slices should increase based on # of cats. Use "setInterval()"

**Comment by talbdbd** [comment]
building the function and I'll have it ready for review tomorrow (Wednesday, Mar 20).

**Comment by talbdbd** [comment]
function complete and ready to push as soon as we resolve git issue

**Comment by talbdbd** [comment]
pushed and merged
